services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: mage-duel-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    ports:
      - "5432:5432"
    networks:
      - mage-duel-network
    restart: unless-stopped

  # PHP Web приложение
  web:
    build: .
    container_name: mage-duel-web
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=admin
      - DB_PASSWORD=1
      - DB_PORT=5432
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    networks:
      - mage-duel-network
    restart: unless-stopped

  # WebSocket сервер
  websocket:
    build: .
    container_name: mage-duel-websocket
    depends_on:
      - postgres
    command: php server.php
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=admin
      - DB_PASSWORD=1
      - DB_PORT=5432
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8081
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:8081"
    networks:
      - mage-duel-network
    restart: unless-stopped

  # Nginx (опционально, для продакшена)
  nginx:
    image: nginx:alpine
    container_name: mage-duel-nginx
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mage-duel-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local

networks:
  mage-duel-network:
    driver: bridge
